apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sharay-fastapi
  namespace: sharay
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: sharay-fastapi.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sharay-fastapi
                port:
                  number: 80
